FROM node AS build
WORKDIR /app

COPY package.json .
COPY tsconfig.json .

RUN npm install

COPY ./client ./client
COPY ./shared ./shared

# ARG CONFIGURATION
WORKDIR client
RUN npm run-script build

# # production environment
FROM nginx
COPY --from=build /app/client/dist /usr/share/nginx/html
COPY --from=build /app/client/nginx.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]